---
title: Evolutionary Genomics and Bioinformatics - FA20
author: Berent Aldikacti
date: "09/27/2020"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
bibliography: data/references.bib
---

This is rendering hmtl files from the course repository  (https://github.com/jeffreyblanchard/evogeno) for Evolutionary Genomics & Bioinformatics taught at the University of Massachusetts Amherst in Fall 2020 by Prof. Jeffrey Blanchard

## Labs

### R Basics

* 1 : [Introduction to R and Reproducible Research](Lab1_BA.html)
* 2 : [git, GitHub and Rstudio project](Lab2_BA.html)
* 5.1 : [Data visualization with ggplot2](Lab5.1-R_BA.html)
* 5.2 : [Lab5 Exercises](Lab5.2-R_BA.html)
* 6 : [Data Maps and Interactive Graphs from the COVID-19 reporting data](Lab6-R_BA.html)

### Python Basics
* 3.2 : [Short Introduction to Programming in Python](Lab3-2_BA.html)
* 3.3 : [Starting with Data](Lab3-3-Python_BA.html)
* 3.4 : [Indexing, Slicing and Subsetting DataFrames in Python](Lab3-4-Python_BA.html)
* 4.1 : [Data Types and Formats](Lab4-1-Python_BA.html)
* 4.2 : [Combining DataFrames and Pandas](Lab4-2-Python_BA.html)
* 4.3 : [Data Workflows and Automation](Lab4-3-Python_BA.html)
* 4.4 : [Making Plots with plotnine](Lab4-4-Python_BA.html)
* 5.1 : [Data Ingest and Visualization - Matplotlib and Pandas](Lab5-1-Python_BA.html)
* 5.2 : [Accessing SQLite Databases Using Python and Pandas](Lab5-2-Python_BA.html)

